config/routes.rb
Rails.application.routes.draw do
    get 'ask/index'
    get 'login', to: 'login#new'
    get 'login/profile', to: 'login#profile', as: :profile_login
    post 'login/profile', to: 'login#update', as: :update_login
    get 'login/create', to: 'login#create', as: :create_login
    get 'login/delete', to: 'login#delete', as: :delete_login
    get 'threads' => 'comments#threads'
      
    resources :submissions
    resources :posts do
      resources :likes and
      put 'like', on: :member and
      put 'unlike', on: :member and
      post 'comment', on: :member and
      resources :comments
    end
    
    resources :comments do
      post 'comment', on: :member and
      resources :comments 
      resources :commentlikes
    end
    root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, as: :commentable
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy comment like unlike]

  # GET /posts or /posts.json
  def index
    if !params[:ask].nil? && params[:ask]
      @posts = Post.where(url: "")
    elsif !params[:newest].nil? && params[:newest]
      @posts = Post.all.sort { |a, b| -a.created_at.to_i <=> -b.created_at.to_i }
    else
      @posts = Post.all.sort { |a, b| -a.points <=> -b.points }
    end
  end
  
  def ask
    @postsask = Post.where(url: "")
  end 
  
  # GET /posts/1 or /posts/1.json
  def show
    @comments = Comment.all
    @users = User.all
  end

  # GET /posts/new
  def new
    @post = Post.new
    if cookies.signed[:user_id].nil?
      redirect_to(login_path)
    end
  end
  
  # PUT /posts/1/comment
  def comment
    if cookies.signed[:user_id].nil?
      redirect_to(login_path)
    
    else
      @post.numcomments += 1;
      @comment = @post.comments.create(content: params[:content], user_id: params[:user_id], post_id: params[:post_id]) #supuestamente el id del post ya está asociado a comment
      
      redirect_to (@post)
    end
  end

  # GET /posts/1/edit
  def edit
  end

  #Hauria de trobar la manera d'identificar si l'usuari actual ha donat like o no per quan tinguem un login
  #Em dona error de Nil class com si el que li passés de l'índex estigués buit
  def like
    @post.points = @post.points + 1
    @post.save
    respond_to do |format|
      format.html { redirect_to "/posts"}
      format.json { head :no_content }
    end
  end
  
  # Encara no comprovat pq no puc treure el like que no he posat abans
  def unlike
    @post.points = @post.points - 1
    @post.save
    respond_to do |format|
      format.html { redirect_to "/posts"}
      format.json { head :no_content }
    end
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    if !Post.find_by(url: @post.url).nil?
      redirect_to(Post.find_by(url: @post.url))
    else
      
      
      content = nil
      if !@post.url.nil? && !@post.url.empty? && !@post.content.nil? && !@post.content.empty?
        content = @post.content
        @post.content = ""
      end
      respond_to do |format|
        if @post.save
          if !content.nil?
            @post.numcomments += 1;
            author_id = User.find_by(name: @post.author).id
            @comment = @post.comments.create(content: content, user_id: author_id, post_id: @post.id)
          end
          format.html { redirect_to "/posts?newest=true", notice: "Post was successfully created." }
          format.json { head :no_content }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.permit(:created_at, :updated_at,  :title, :content, :author, :url, :id_post)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :points %>
    <%= f.number_field :points %>
  </div>

  <div class="field">
    <%= f.label :numcomments %>
    <%= f.number_field :numcomments %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<table border="0" cellpadding="0" cellspacing="0" class="itemlist">
  <tbody>
    <% @posts.each_with_index do |post, index| %>
      <tr class="athing" id="28940860">
        <td align="right" valign="top" class="title">
          <span class="rank"><%= index+1 %>.</span>
        </td>
        <td valign="top" class="votelinks">
          <center>
            <% if cookies.signed[:user_id].nil? %>
              <div class="votearrow" title="vota"><%= link_to "\u00A0\u00A0", login_path, method: :get %></div>
            <% else %>
              <div class="votearrow" title="vota"><%= link_to "\u00A0\u00A0", post_likes_path(post), method: :post %></div>
            <% end %>
            <!--<div class="votearrow" title="vota">< %= link_to "\u00A0\u00A0", post_likes_path(post), method: :post %></div> <!-- potser el post que li passem hauria de ser amb @ (pel que fa el tutorial)
            <div class="votearrow" title="upvote">< %= link_to '_', like_post_path(post), method: :put %></div>-->
          </center>
        </td>
       <td class="title">
          <% if !post.url.nil? && !post.url.empty? %>
          <a href="https://<%= post.url.gsub("https://", "").gsub("http://", "") %>"><%= post.title %></a>
          <span class="sitebit comhead"> (<a href="https://<%= post.url.gsub("https://", "").gsub("http://", "").split('/').first %>"><span class="sitestr"><%= post.url.gsub("https://", "").gsub("http://", "").split('/').first %></span></a>)</span>
          <% else %>
          <%= link_to post.title, post, :style=> 'color:black;' %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td class="subtext">
          <span class="score" id="score"><%= post.likes.count %> points</span>
          <!--<span class="score" id="score">< %= post.points %> points</span>-->
          by <a href="<%= profile_login_path(:name => post.author) %>" class="hnuser"><%= post.author %></a> 
          <span class="age" title="time_ago"><%= time_ago_in_words(post.created_at)  %> ago</span> 
          <span id="unv_28940860"></span> | <% pre_like = post.likes.find { |like| like.user_id == cookies.signed[:user_id]} %> <% if pre_like %> <%= link_to 'unlike', post_like_path(post, pre_like), method: :delete %>  | <% end %><%= link_to "#{post.comments.length()} comments", post %></a>
          <!--<span id="unv_28940860"></span> | <a href="" onclick="">hide</a> | < %= link_to 'unlike', unlike_post_path(post), method: :put %> | < %= link_to 'Show', post %> < %= post.numcomments %> comments</a>-->
        </td>
      </tr>
      <tr class="spacer" style="height:5px"></tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<form method="post" action="/posts">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <%= hidden_field_tag :created_at, DateTime.now() %>
  <%= hidden_field_tag :updated_at, DateTime.now() %>
  <%= hidden_field_tag :id_post, Time.now.to_i %>
  <%= hidden_field_tag :author, User.find(cookies.signed[:user_id]).name %>
  <table border="0">
    <tr>
      <td>title</td>
      <td>
        <input
          type="text"
          name="title"
          value=""
          size="50"
          autofocus="t"
        /><span style="margin-left:10px"></span>
      </td>
    </tr>
    <tr>
      <td>url</td>
      <td><input type="url" name="url" value="" size="50" /></td>
    </tr>
    <tr>
      <td></td>
      <td><b>or</b></td>
    </tr>
    <tr>
      <td>text</td>
      <td><textarea name="content" rows="4" cols="49"></textarea></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td><input type="submit" value="submit"></td>
    </tr>
    <tr style="height:20px"></tr>
    <tr>
      <td></td>
      <td>Leave url blank to submit a question for discussion. If there
        is no url, the text (if any) will appear at the top of the
        thread.<br><br>
        You can also submit via bookmarklet</a>.
      </td>
    </tr>
  </table>
</form>

app/views/posts/show.html.erb
            <table class="fatitem" border="0">
                <tbody>
                  <tr class="athing" id="29016506">
                    <td align="right" valign="top" class="title">
                      <span class="rank"></span>
                    </td>      
                    <td valign="top" class="votelinks">
                      <center>
                        <a id="up_29016506" href="CANVIAR"> <!-- link a upvote -->
                          <% if cookies.signed[:user_id].nil? %>
                            <div class="votearrow" title="vota"><%= link_to "\u00A0\u00A0", login_path, method: :get %></div>
                          <% else %>
                            <div class="votearrow" title="vota"><%= link_to "\u00A0\u00A0", post_likes_path(@post), method: :post %></div>
                          <% end %>
                        </a>
                      </center>
                    </td>
                    <td class="title">
                      <a href="" class="titlelink" style="color:black"><%= @post.title %></a>
                      <span class="sitebit comhead"> </span>
                    </td>
                  </tr>
                  <tr>
                    <td colspan="2"></td>
                    <td class="subtext">
                      <span class="score" id="score_29016506"><%= @post.likes.count %> points</span> 
                        by <a href="<%= profile_login_path(:name => @post.author) %>" class="hnuser"><%= @post.author %></a> 
                      <span class="age" title="<%@post.created_at%>">
                        <a href="CANVIAR"><%= time_ago_in_words(@post.created_at)  %> ago</a></span> <!-- no entenc on se suposa que porta-->
                      <span id="unv_29016506">
                        | <%= @post.comments.length() %>&nbsp;comments <% pre_like = @post.likes.find { |like| like.user_id == cookies.signed[:user_id]} %> <% if pre_like %> | <%= link_to 'unlike', post_like_path(@post, pre_like), method: :delete %><% end %>
                      </span> 
                           <!-- el link ha de portar a la pg actual -->              
                    </td></tr>
                  <tr>
                    <td colspan="2"></td>
                    <td><%= @post.content %></td>
                  </tr>
                  <tr>
                    <td colspan="2"></td>
                    <td>
                    <form method="post" action="<%= comment_post_path(@post) %>">
                      <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
                         
                        <% if cookies.signed[:user_id].nil? %> 
                          <a id="login" href="<%= login_path %>"></a>
                        <% else %>
                          <%= hidden_field_tag :user_id, User.find(cookies.signed[:user_id]).id %>
                        <% end %>
                        <%= hidden_field_tag :post_id, @post.id %>
                        <textarea name="content" rows="6" cols="60"></textarea>
                        <br><br>
                        <input type="submit" value="add comment">
                      </form>
                    </td></tr></table>
            <br>
            <table border="0" class="comment-tree">
              <tbody>
                <tr class="comment" id="CANVIAR"> 
                  <td>
                    <table border="0">
                      <tbody>
                        <ul>
                          <%= render partial: 'comments/comment', collection: @post.comments %>
                        </ul>  
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
      