hacker_news/config/routes.rb
Rails.application.routes.draw do
    get 'login', to: 'login#new'
    get 'login/profile', to: 'login#profile', as: :profile_login
    post 'login/profile', to: 'login#update', as: :update_login
    get 'login/create', to: 'login#create', as: :create_login
    get 'login/delete', to: 'login#delete', as: :delete_login
    get '/usuaris', to: 'login#usuaris', as: :usuaris_login
    post '/usuaris', to: 'login#update', as: :edit_login
      
    resources :submissions
    resources :posts do
      resources :likes and
      put 'like', on: :member and
      put 'unlike', on: :member and
      post 'comment', on: :member and
      resources :comments
    end
    
    resources :comments do
      post 'comment', on: :member and
      resources :comments 
      resources :commentlikes
    end
    root 'posts#index'
end

hacker_news/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy comment like unlike]

  # GET /posts or /posts.json
  def index
    if !params[:type].nil? && params[:type] == 'ask'
      @posts = Post.where(url: "").sort { |a, b| -a.points <=> -b.points }
    elsif !params[:type].nil? && params[:type] == 'newest'
      @posts = Post.all.sort { |a, b| -a.created_at.to_i <=> -b.created_at.to_i }
    elsif !params[:author].nil?
      user = User.find_by(name: params[:author])
      if user.nil?
        respond_to do |format|
          format.html
          format.json { head :bad_request }
        end
        return
      end
      @posts = Post.where(author_id: user.id).sort { |a, b| -a.points <=> -b.points }
    elsif !params[:upvoted_by].nil?
      user = User.find_by(name: params[:upvoted_by])
      if user.nil?
        respond_to do |format|
          format.html
          format.json { head :bad_request }
        end
        return
      end
      likedPostIds = Like.where(user_id: user.id).select(:post_id).to_a.map{|l| l.post_id}
      @posts = Post.where(id: likedPostIds).sort { |a, b| -a.points <=> -b.points }
    else
      @posts = Post.all.sort { |a, b| -a.points <=> -b.points }
    end
    if request.format.json?
      posts_json = @posts.as_json
      key   = ActiveSupport::KeyGenerator.new(ENV['SECRET_KEY']).generate_key(ENV['ENCRYPTION_SALT'], ActiveSupport::MessageEncryptor.key_len)
      crypt = ActiveSupport::MessageEncryptor.new(key)
      auth_user_id = crypt.decrypt_and_verify(params['X-API-KEY'])
      posts_json.map{ |postp| postp[:voted_by_auth] = Like.where(post_id: postp['id'], user_id: auth_user_id).count != 0; postp }
      respond_to do |format|
        format.html
        format.json { render json: posts_json }
      end
    end
  end
  
  def ask
    @postsask = Post.where(url: "")
  end 
  
  # GET /posts/1 or /posts/1.json
  def show
    @comments = Comment.all
    @users = User.all
    if request.format.json?
      post_json = @post.as_json
      key   = ActiveSupport::KeyGenerator.new(ENV['SECRET_KEY']).generate_key(ENV['ENCRYPTION_SALT'], ActiveSupport::MessageEncryptor.key_len)
      crypt = ActiveSupport::MessageEncryptor.new(key)
      auth_user_id = crypt.decrypt_and_verify(params['X-API-KEY'])
      post_json[:voted_by_auth] = Like.where(post_id: post_json['id'], user_id: auth_user_id).count != 0
      respond_to do |format|
        format.html
        format.json { render json: post_json }
      end
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
    if cookies.signed[:user_id].nil?
      redirect_to(login_path)
    end
  end
  
  # PUT /posts/1/comment
  def comment
    if request.format.json?
      respond_to do |format|
          format.html
          format.json { head :bad_request }
        end
        return
    else
      if cookies.signed[:user_id].nil?
        redirect_to(login_path)
      else
        if !params[:content].nil? && !params[:content].blank?
          @post.numcomments += 1;
          @comment = @post.comments.create(content: params[:content], user_id: params[:user_id], post_id: params[:post_id]) #supuestamente el id del post ya está asociado a comment
          redirect_to @post
        end
      end
    end
  end

  # GET /posts/1/edit
  def edit
  end

  #Hauria de trobar la manera d'identificar si l'usuari actual ha donat like o no per quan tinguem un login
  #Em dona error de Nil class com si el que li passés de l'índex estigués buit
  def like
    p 'Liking?'
    @post.points = @post.points + 1
    @post.save
    respond_to do |format|
      format.html { redirect_to "/posts"}
      format.json { head :no_content }
    end
  end
  
  # Encara no comprovat pq no puc treure el like que no he posat abans
  def unlike
    @post.points = @post.points - 1
    @post.save
    respond_to do |format|
      format.html { redirect_to "/posts"}
      format.json { head :no_content }
    end
  end

  # POST /posts or /posts.json
  def create
    author_id = nil
    if request.format.json?
      if params['X-API-KEY'].nil?
        respond_to do |format|
          format.html
          format.json { head :unauthorized }
        end
        return
      else
        key   = ActiveSupport::KeyGenerator.new(ENV['SECRET_KEY']).generate_key(ENV['ENCRYPTION_SALT'], ActiveSupport::MessageEncryptor.key_len)
        crypt = ActiveSupport::MessageEncryptor.new(key)
        author_id = crypt.decrypt_and_verify(params['X-API-KEY'])
        if author_id.nil?
          respond_to do |format|
            format.html
            format.json { head :unauthorized }
          end
          return
        end
      end
    end
    
    @post = Post.new(post_params)
    if !author_id.nil?    #si el author no es nulo
      @post.author_id = author_id
    end
    if !@post.url.nil? && !@post.url.empty? && !Post.find_by(url: @post.url).nil?     #si existe un post con el url 
      redirect_to(Post.find_by(url: @post.url))
    else
      content = nil
      if !@post.url.nil? && !@post.url.empty? && !@post.content.nil? && !@post.content.empty?
        content = @post.content
        @post.content = ""
      end
      respond_to do |format|
        if @post.save
          if !content.nil?
            @post.numcomments += 1;
            @comment = @post.comments.create(content: content, user_id: @post.author_id, post_id: @post.id)
          end
          format.html { redirect_to "/posts?newest=true", notice: "Post was successfully created." }
          format.json { render json: @post}
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.permit(:created_at, :updated_at,  :title, :content, :author_id, :url, :id_post)
    end
  end

hacker_news/app/views/posts/_comment.html.erb
<tr>
    <td class="ind" indent="0">
        <img src="s.gif" height="1" width="0">
    </td>
    <td valign="top" class="votelinks">
        <center>
            <a id="up_29151509" href="CANVIAR"> <!-- link a upvote -->
                <div class="votearrow" title="upvote"></div>
            </a>
        </center>
    </td>
                          
    <td class="default">
        <div style="margin-top:2px; margin-bottom:-10px;">
            <span class="comhead">
                <a href="CANVIAR" class="hnuser"> <%= comment.user_id%> </a> <!-- link a usuari, canviar amb cookies pq surti el nom-->
                    <span class="age" title="2021-11-08T17:15:34">
                        <%= time_ago_in_words(comment.created_at)  %> ago
                    </span> 
                    <span id="unv_29151509"></span>
                    </span>
        </div>
        <br>
        <div class="comment">
            <span class="commtext c00">
                <%= comment.content %>
                <div class="reply">        
                    <p>
                        <font size="1">
                            <u>
                                
                                <a><%= link_to "reply", comment_path(comment) %> </a>
                            </u> <!-- link a fer el reply -->
                        </font>
                    </p>
                 </div>
            </span>
            <ul>
                <%= render partial: 'posts/comment', collection: comment.comments %>
            </ul>
        </div>
    </td>
</tr>

hacker_news/app/views/posts/index.html.erb
<table border="0" cellpadding="0" cellspacing="0" class="itemlist">
  <tbody>
    <% @posts.each_with_index do |post, index| %>
      <tr class="athing" id="28940860">
        <td align="right" valign="top" class="title">
          <span class="rank"><%= index+1 %>.</span>
        </td>
        <td valign="top" class="votelinks">
          <center>
            <% if cookies.signed[:user_id].nil? %>
              <div class="votearrow" title="vota"><%= link_to "\u00A0\u00A0", login_path, method: :get %></div>
            <% elsif User.find(cookies.signed[:user_id]).id == post.author_id %>
                <div><font color="#ff6600">*</font></div>
            <% else %>
              <% pre_like = post.likes.find { |like| like.user_id == cookies.signed[:user_id]} %> 
              <% if pre_like %>
                <div class="voterrow" title="vota" style="width: 14px; height:19px;"></div>
              <% else %>
                <div class="votearrow" title="vota"><%= link_to "\u00A0\u00A0", post_likes_path(post), method: :post %></div>
              <% end %>
            <% end %>
            <!--<div class="votearrow" title="vota">< %= link_to "\u00A0\u00A0", post_likes_path(post), method: :post %></div> <!-- potser el post que li passem hauria de ser amb @ (pel que fa el tutorial)
            <div class="votearrow" title="upvote">< %= link_to '_', like_post_path(post), method: :put %></div>-->
          </center>
        </td>
       <td class="title">
          <% if !post.url.nil? && !post.url.empty? %>
          <a href="https://<%= post.url.gsub("https://", "").gsub("http://", "") %>" style="color:black"><%= post.title %></a>
          <span class="sitebit comhead"> (<a href="https://<%= post.url.gsub("https://", "").gsub("http://", "").split('/').first %>"><span class="sitestr"><%= post.url.gsub("https://", "").gsub("http://", "").split('/').first %></span></a>)</span>
          <% else %>
          <%= link_to post.title, post, :style=> 'color:black;' %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td class="subtext">
          <span class="score" id="score"><%= post.likes.count %> points</span>
          <!--<span class="score" id="score">< %= post.points %> points</span>-->
          by <a href="<%= profile_login_path(:name => User.find(post.author_id).name) %>" class="hnuser"><%= User.find(post.author_id).name %></a> 
          <span class="age" title="time_ago"><%= time_ago_in_words(post.created_at)  %> ago</span> 
          <span id="unv_28940860"></span> | <% pre_like = post.likes.find { |like| like.user_id == cookies.signed[:user_id]} %> <% if pre_like %> <%= link_to 'unlike', post_like_path(post, pre_like), method: :delete %>  | <% end %><%= link_to "#{post.comments.length()} comments", post %></a>
          <!--<span id="unv_28940860"></span> | <a href="" onclick="">hide</a> | < %= link_to 'unlike', unlike_post_path(post), method: :put %> | < %= link_to 'Show', post %> < %= post.numcomments %> comments</a>-->
        </td>
      </tr>
      <tr class="spacer" style="height:5px"></tr>
    <% end %>
  </tbody>
</table>

hacker_news/app/views/posts/new.html.erb
<form method="post" action="/posts">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <%= hidden_field_tag :created_at, DateTime.now() %>
  <%= hidden_field_tag :updated_at, DateTime.now() %>
  <%= hidden_field_tag :id_post, Time.now.to_i %>
  <%= hidden_field_tag :author_id, cookies.signed[:user_id] %>
  <table border="0">
    <tr>
      <td>title</td>
      <td>
        <input
          type="text"
          name="title"
          value=""
          size="50"
          autofocus="t"
        /><span style="margin-left:10px"></span>
      </td>
    </tr>
    <tr>
      <td>url</td>
      <td><input type="url" name="url" value="" size="50" /></td>
    </tr>
    <tr>
      <td></td>
      <td><b>or</b></td>
    </tr>
    <tr>
      <td>text</td>
      <td><textarea name="content" rows="4" cols="49"></textarea></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td><input type="submit" value="submit"></td>
    </tr>
    <tr style="height:20px"></tr>
    <tr>
      <td></td>
      <td>Leave url blank to submit a question for discussion. If there
        is no url, the text (if any) will appear at the top of the
        thread.<br><br>
        You can also submit via bookmarklet</a>.
      </td>
    </tr>
  </table>
</form>

hacker_news/app/views/posts/show.html.erb
            <table class="fatitem" border="0">
                <tbody>
                  <tr class="athing" id="29016506">
                    <td align="right" valign="top" class="title">
                      <span class="rank"></span>
                    </td>      
                    <td valign="top" class="votelinks">
                      <center>
                          <% if cookies.signed[:user_id].nil? %>
                            <a id="up_29016506" href="CANVIAR">
                            <div class="votearrow" title="vota"><%= link_to "\u00A0\u00A0", login_path, method: :get %></div>
                            </a>
                           <% elsif User.find(cookies.signed[:user_id]).id == @post.author_id %>
                              <div><font color="#ff6600">*</font></div>
                          <% else %>
                            <a id="up_29016506" href="CANVIAR">
                            <% pre_like = @post.likes.find { |like| like.user_id == cookies.signed[:user_id]} %> 
                            <% if pre_like %>
                              <div class="voterrow" title="vota" style="width: 16px;"></div>
                            <% else %>
                              <div class="votearrow" title="vota" style="width: 12px;"><%= link_to "\u00A0\u00A0", post_likes_path(@post), method: :post %></div>
                            <% end %>
                            </a>
                          <% end %>
                      </center>
                    </td>
                    <td class="title">
                      <a href="" class="titlelink" style="color:black"><%= @post.title %></a>
                      <span class="sitebit comhead"> </span>
                    </td>
                  </tr>
                  <tr>
                    <td colspan="2"></td>
                    <td class="subtext">
                      <span class="score" id="score_29016506"><%= @post.likes.count %> points</span> 
                       by <a href="<%= profile_login_path(:name => User.find(@post.author_id).name) %>" class="hnuser"><%= User.find(@post.author_id).name %></a> 
                      <span class="age" title="<%@post.created_at%>">
                        <a href="CANVIAR"><%= time_ago_in_words(@post.created_at)  %> ago</a></span> <!-- no entenc on se suposa que porta-->
                      <span id="unv_29016506">
                        | <%= @post.comments.length() %>&nbsp;comments <% pre_like = @post.likes.find { |like| like.user_id == cookies.signed[:user_id]} %> <% if pre_like %> | <%= link_to 'unlike', post_like_path(@post, pre_like), method: :delete %><% end %>
                      </span> 
                           <!-- el link ha de portar a la pg actual -->              
                    </td></tr>
                  <tr>
                    <td colspan="2"></td>
                    <td><%= @post.content %></td>
                  </tr>
                  <tr>
                    <td colspan="2"></td>
                    <td>
                    <form method="post" action="<%= comment_post_path(@post) %>">
                      <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
                         
                        <% if cookies.signed[:user_id].nil? %> 
                          <a id="login" href="<%= login_path %>"></a>
                        <% else %>
                          <%= hidden_field_tag :user_id, User.find(cookies.signed[:user_id]).id %>
                        <% end %>
                        <%= hidden_field_tag :post_id, @post.id %>
                        <textarea name="content" rows="6" cols="60"></textarea>
                        <br><br>
                        <input type="submit" value="add comment">
                      </form>
                    </td></tr></table>
            <br>
            <table border="0" class="comment-tree">
              <tbody>
                <tr class="comment" id="CANVIAR"> 
                  <td>
                    <table border="0">
                      <tbody>
                        <ul>
                          <%= render partial: 'comments/comment', collection: @post.comments %>
                        </ul>  
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
      