config/routes.rb
Rails.application.routes.draw do
    get 'ask/index'
    get 'login', to: 'login#new'
    get 'login/profile', to: 'login#profile', as: :profile_login
    post 'login/profile', to: 'login#update', as: :update_login
    get 'login/create', to: 'login#create', as: :create_login
    get 'login/delete', to: 'login#delete', as: :delete_login
    get 'threads' => 'comments#threads'
      
    resources :submissions
    resources :posts do
      resources :likes and
      put 'like', on: :member and
      put 'unlike', on: :member and
      post 'comment', on: :member and
      resources :comments
    end
    
    resources :comments do
      post 'comment', on: :member and
      resources :comments 
      resources :commentlikes
    end
    root 'posts#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackerNews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <center>
      <table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
        <tbody>
          <tr>
            <td bgcolor="#ff6600">
              <table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px">
                <tbody>
                  <tr>
                    <td style="width:18px;padding-right:4px"><a href="<%= posts_path %>"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
                    <td style="line-height:12pt; height:10px;">
                      <span class="pagetop">
                        <b class="hnname"><a href="<%= posts_path %>">Hacker News</a></b>
                        <a href="<%= posts_path(:newest => true) %>">newest</a>
                        | <a href="<%= new_post_path %>">submit</a>
                        | <a href="<%= posts_path(:ask => true) %>">ask</a>
                        | <a href="<%= threads_path %>">threads</a>
                      </span>
                    </td>
                    <td style="text-align:right;padding-right:4px;">
                      <span class="pagetop">
                        <% if cookies.signed[:user_id].nil? %> 
                          <a id="login" href="<%= login_path %>">signup/login</a>
                        <% else %>
                          <a id="me" href="<%= profile_login_path(:name => User.find(cookies.signed[:user_id]).name) %>"><%= User.find(cookies.signed[:user_id]).name %></a> | <a id="logout" href="<%= delete_login_path %>">logout</a>
                        <% end %>
                      </span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
          <tr id="pagespace" title="" style="height:10px"></tr>
          <tr>
            <td>
              <%= yield %>
            </td>
          </tr>
          <tr>
          <td>
            <img src="s.gif" height="10" width="0">
              <table width="100%" cellspacing="0" cellpadding="1">
                <tbody>
                  <tr>
                    <td bgcolor="#ff6600"></td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </tbody>
      </table>
    </center>
  </body>
</html>